# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "lucid64"
  config.vm.share_folder "puppet", "/puppet/", "../manifests/"
  config.vm.host_name = "node2"

  # The url from where the 'c
  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :hostonly, "192.168.33.30"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../manifests/"
    puppet.manifest_file  = "base.pp"
  end
end
